apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: argocd
  source:
    path: kind-cluster/appprojects
    repoURL: https://github.com/zacharyzhuo/argocd-app-demo.git
    targetRevision: master
    directory:
      recurse: true
      jsonnet: {}
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
