apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/zacharyzhuo/argocd-app-demo.git
    path: charts/apps/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true