apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-appprojects
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: argocd
  source:
    path: appprojects
    repoURL: git@github.com:zacharyzhuo/argocd-app-demo.git
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
