apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: common
  namespace: argocd
spec:
  description: Common Project
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: prometheus
      server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
    - "*"
